#!/bin/sh -eu

mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS `test`;'
mysql -uroot test -e 'CREATE TABLE IF NOT EXISTS `user` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `first_name` VARCHAR(64) NOT NULL, `last_name` VARCHAR(64) NOT NULL, `gender` SMALLINT NOT NULL, `age` INT NOT NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(`id`)) ENGINE=InnoDB;'
